services:

  postgres:
    image: postgres:15-alpine
    container_name: dudes-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dudes
      - POSTGRES_USER=dudes
      - POSTGRES_DB=dudes

  nginx:
    image: nginx:alpine
    container_name: dudes-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/html
    restart: always

volumes:
  postgres-data:
